<?php
/**
 * AccountStatResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Cakemail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cakemail API
 *
 * The Cakemail API exposes multiple APIs including Authentication, Marketing, Contact, Transactional, Analytic, Content, Account and Partner.
 *
 * The version of the OpenAPI document: 1.0.0-alpha5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Cakemail;

use PHPUnit\Framework\TestCase;

/**
 * AccountStatResponseTest Class Doc Comment
 *
 * @category    Class
 * @description AccountStatResponse
 * @package     Cakemail
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AccountStatResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AccountStatResponse"
     */
    public function testAccountStatResponse()
    {
    }

    /**
     * Test attribute "active_contacts"
     */
    public function testPropertyActiveContacts()
    {
    }

    /**
     * Test attribute "sent_emails"
     */
    public function testPropertySentEmails()
    {
    }

    /**
     * Test attribute "sent_campaign_emails"
     */
    public function testPropertySentCampaignEmails()
    {
    }

    /**
     * Test attribute "sent_action_emails"
     */
    public function testPropertySentActionEmails()
    {
    }

    /**
     * Test attribute "sent_email_emails"
     */
    public function testPropertySentEmailEmails()
    {
    }

    /**
     * Test attribute "open_rate"
     */
    public function testPropertyOpenRate()
    {
    }

    /**
     * Test attribute "bounce_rate"
     */
    public function testPropertyBounceRate()
    {
    }

    /**
     * Test attribute "click_rate"
     */
    public function testPropertyClickRate()
    {
    }

    /**
     * Test attribute "spam_rate"
     */
    public function testPropertySpamRate()
    {
    }

    /**
     * Test attribute "unsubscribe_rate"
     */
    public function testPropertyUnsubscribeRate()
    {
    }

    /**
     * Test attribute "emails_usage"
     */
    public function testPropertyEmailsUsage()
    {
    }

    /**
     * Test attribute "contacts_usage"
     */
    public function testPropertyContactsUsage()
    {
    }

    /**
     * Test attribute "bounces_hard"
     */
    public function testPropertyBouncesHard()
    {
    }

    /**
     * Test attribute "bounce_hard_rate"
     */
    public function testPropertyBounceHardRate()
    {
    }

    /**
     * Test attribute "spams"
     */
    public function testPropertySpams()
    {
    }

    /**
     * Test attribute "current_lists"
     */
    public function testPropertyCurrentLists()
    {
    }
}
