<?php
/**
 * ListStatResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Cakemail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cakemail API
 *
 * The Cakemail API exposes multiple APIs including Authentication, Marketing, Contact, Transactional, Analytic, Content, Account and Partner.
 *
 * The version of the OpenAPI document: 1.0.0-alpha5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Cakemail;

use PHPUnit\Framework\TestCase;

/**
 * ListStatResponseTest Class Doc Comment
 *
 * @category    Class
 * @description ListStatResponse
 * @package     Cakemail
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ListStatResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ListStatResponse"
     */
    public function testListStatResponse()
    {
    }

    /**
     * Test attribute "active_contacts"
     */
    public function testPropertyActiveContacts()
    {
    }

    /**
     * Test attribute "pending_contacts"
     */
    public function testPropertyPendingContacts()
    {
    }

    /**
     * Test attribute "invalid_contacts"
     */
    public function testPropertyInvalidContacts()
    {
    }

    /**
     * Test attribute "unsubscribed_contacts"
     */
    public function testPropertyUnsubscribedContacts()
    {
    }

    /**
     * Test attribute "flagged_contacts"
     */
    public function testPropertyFlaggedContacts()
    {
    }

    /**
     * Test attribute "deleted_contacts"
     */
    public function testPropertyDeletedContacts()
    {
    }

    /**
     * Test attribute "sent_emails"
     */
    public function testPropertySentEmails()
    {
    }

    /**
     * Test attribute "open_rate"
     */
    public function testPropertyOpenRate()
    {
    }

    /**
     * Test attribute "bounce_rate"
     */
    public function testPropertyBounceRate()
    {
    }

    /**
     * Test attribute "click_rate"
     */
    public function testPropertyClickRate()
    {
    }

    /**
     * Test attribute "unsubscribe_rate"
     */
    public function testPropertyUnsubscribeRate()
    {
    }

    /**
     * Test attribute "spam_rate"
     */
    public function testPropertySpamRate()
    {
    }
}
