<?php
/**
 * PatchCampaignTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Cakemail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cakemail API
 *
 * The Cakemail API exposes multiple APIs including Authentication, Marketing, Contact, Transactional, Analytic, Content, Account and Partner.
 *
 * The version of the OpenAPI document: 1.0.0-alpha5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Cakemail;

use PHPUnit\Framework\TestCase;

/**
 * PatchCampaignTest Class Doc Comment
 *
 * @category    Class
 * @description PatchCampaign
 * @package     Cakemail
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PatchCampaignTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PatchCampaign"
     */
    public function testPatchCampaign()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "audience"
     */
    public function testPropertyAudience()
    {
    }

    /**
     * Test attribute "tracking"
     */
    public function testPropertyTracking()
    {
    }

    /**
     * Test attribute "sender"
     */
    public function testPropertySender()
    {
    }

    /**
     * Test attribute "reply_to_email"
     */
    public function testPropertyReplyToEmail()
    {
    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {
    }

    /**
     * Test attribute "editor"
     */
    public function testPropertyEditor()
    {
    }
}
