<?php
/**
 * SendTestEmailResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Cakemail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cakemail API
 *
 * The Cakemail API exposes multiple APIs including Authentication, Marketing, Contact, Transactional, Analytic, Content, Account and Partner.
 *
 * The version of the OpenAPI document: 1.0.0-alpha5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Cakemail;

use PHPUnit\Framework\TestCase;

/**
 * SendTestEmailResponseTest Class Doc Comment
 *
 * @category    Class
 * @description SendTestEmailResponse
 * @package     Cakemail
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SendTestEmailResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SendTestEmailResponse"
     */
    public function testSendTestEmailResponse()
    {
    }

    /**
     * Test attribute "test_email"
     */
    public function testPropertyTestEmail()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "object"
     */
    public function testPropertyObject()
    {
    }

    /**
     * Test attribute "sent"
     */
    public function testPropertySent()
    {
    }
}
