<?php
/**
 * CampaignApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Cakemail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cakemail API
 *
 * The Cakemail API exposes multiple APIs including Authentication, Marketing, Contact, Transactional, Analytic, Content, Account and Partner.
 *
 * The version of the OpenAPI document: 1.0.0-alpha5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Cakemail;

use \Cakemail\Configuration;
use \Cakemail\ApiException;
use \Cakemail\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CampaignApiTest Class Doc Comment
 *
 * @category Class
 * @package  Cakemail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CampaignApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for archiveCampaign
     *
     * Archive a campaign.
     *
     */
    public function testArchiveCampaign()
    {
    }

    /**
     * Test case for cancelCampaign
     *
     * Cancel a campaign.
     *
     */
    public function testCancelCampaign()
    {
    }

    /**
     * Test case for createCampaign
     *
     * Create a campaign.
     *
     */
    public function testCreateCampaign()
    {
    }

    /**
     * Test case for deleteCampaign
     *
     * Delete a campaign.
     *
     */
    public function testDeleteCampaign()
    {
    }

    /**
     * Test case for getCampaign
     *
     * Show a campaign details.
     *
     */
    public function testGetCampaign()
    {
    }

    /**
     * Test case for listCampaigns
     *
     * Show all campaigns.
     *
     */
    public function testListCampaigns()
    {
    }

    /**
     * Test case for listLinks
     *
     * Show a campaign links.
     *
     */
    public function testListLinks()
    {
    }

    /**
     * Test case for patchCampaign
     *
     * Update a campaign.
     *
     */
    public function testPatchCampaign()
    {
    }

    /**
     * Test case for renderCampaign
     *
     * Render a campaign.
     *
     */
    public function testRenderCampaign()
    {
    }

    /**
     * Test case for rescheduleCampaign
     *
     * Reschedule a campaign.
     *
     */
    public function testRescheduleCampaign()
    {
    }

    /**
     * Test case for resumeCampaign
     *
     * Resume a campaign.
     *
     */
    public function testResumeCampaign()
    {
    }

    /**
     * Test case for scheduleCampaign
     *
     * Schedule a campaign.
     *
     */
    public function testScheduleCampaign()
    {
    }

    /**
     * Test case for sendTestEmail
     *
     * Send a test email.
     *
     */
    public function testSendTestEmail()
    {
    }

    /**
     * Test case for suspendCampaign
     *
     * Suspend a campaign.
     *
     */
    public function testSuspendCampaign()
    {
    }

    /**
     * Test case for unarchiveCampaign
     *
     * Unarchive a campaign.
     *
     */
    public function testUnarchiveCampaign()
    {
    }

    /**
     * Test case for unscheduleCampaign
     *
     * Unschedule a campaign.
     *
     */
    public function testUnscheduleCampaign()
    {
    }
}
