<?php
/**
 * ContactApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Cakemail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cakemail API
 *
 * The Cakemail API exposes multiple APIs including Authentication, Marketing, Contact, Transactional, Analytic, Content, Account and Partner.
 *
 * The version of the OpenAPI document: 1.0.0-alpha5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Cakemail;

use \Cakemail\Configuration;
use \Cakemail\ApiException;
use \Cakemail\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ContactApiTest Class Doc Comment
 *
 * @category Class
 * @package  Cakemail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ContactApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createContact
     *
     * Add a contact in a list.
     *
     */
    public function testCreateContact()
    {
    }

    /**
     * Test case for deleteContact
     *
     * Delete a contact.
     *
     */
    public function testDeleteContact()
    {
    }

    /**
     * Test case for getContact
     *
     * Show a contact details.
     *
     */
    public function testGetContact()
    {
    }

    /**
     * Test case for importContacts
     *
     * Import contacts.
     *
     */
    public function testImportContacts()
    {
    }

    /**
     * Test case for listContactsOfList
     *
     * Show all contacts in a list.
     *
     */
    public function testListContactsOfList()
    {
    }

    /**
     * Test case for listContactsOfSegment
     *
     * Show all contacts in a segment.
     *
     */
    public function testListContactsOfSegment()
    {
    }

    /**
     * Test case for patchContact
     *
     * Update a contact.
     *
     */
    public function testPatchContact()
    {
    }

    /**
     * Test case for unsubscribeContact
     *
     * Unsubscribe a contact from a list.
     *
     */
    public function testUnsubscribeContact()
    {
    }
}
