<?php
/**
 * CustomAttributeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Cakemail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cakemail API
 *
 * The Cakemail API exposes multiple APIs including Authentication, Marketing, Contact, Transactional, Analytic, Content, Account and Partner.
 *
 * The version of the OpenAPI document: 1.0.0-alpha5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Cakemail;

use \Cakemail\Configuration;
use \Cakemail\ApiException;
use \Cakemail\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CustomAttributeApiTest Class Doc Comment
 *
 * @category Class
 * @package  Cakemail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomAttributeApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createCustomAttribute
     *
     * Create a custom attribute.
     *
     */
    public function testCreateCustomAttribute()
    {
    }

    /**
     * Test case for deleteCustomAttribute
     *
     * Delete a custom attribute.
     *
     */
    public function testDeleteCustomAttribute()
    {
    }

    /**
     * Test case for getCustomAttribute
     *
     * Show a custom attribute.
     *
     */
    public function testGetCustomAttribute()
    {
    }

    /**
     * Test case for listCustomAttributes
     *
     * Show all custom attributes.
     *
     */
    public function testListCustomAttributes()
    {
    }
}
