<?php
/**
 * FormApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Cakemail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cakemail API
 *
 * The Cakemail API exposes multiple APIs including Authentication, Marketing, Contact, Transactional, Analytic, Content, Account and Partner.
 *
 * The version of the OpenAPI document: 1.0.0-alpha5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Cakemail;

use \Cakemail\Configuration;
use \Cakemail\ApiException;
use \Cakemail\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FormApiTest Class Doc Comment
 *
 * @category Class
 * @package  Cakemail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FormApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createForm
     *
     * Create a form.
     *
     */
    public function testCreateForm()
    {
    }

    /**
     * Test case for deleteForm
     *
     * Delete a form.
     *
     */
    public function testDeleteForm()
    {
    }

    /**
     * Test case for getForm
     *
     * Show a form details.
     *
     */
    public function testGetForm()
    {
    }

    /**
     * Test case for listForms
     *
     * Show all forms.
     *
     */
    public function testListForms()
    {
    }

    /**
     * Test case for patchForm
     *
     * Update a form.
     *
     */
    public function testPatchForm()
    {
    }
}
