<?php
/**
 * ListApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Cakemail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cakemail API
 *
 * The Cakemail API exposes multiple APIs including Authentication, Marketing, Contact, Transactional, Analytic, Content, Account and Partner.
 *
 * The version of the OpenAPI document: 1.0.0-alpha5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Cakemail;

use \Cakemail\Configuration;
use \Cakemail\ApiException;
use \Cakemail\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ListApiTest Class Doc Comment
 *
 * @category Class
 * @package  Cakemail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ListApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for acceptListPolicy
     *
     * Accept policy for a list.
     *
     */
    public function testAcceptListPolicy()
    {
    }

    /**
     * Test case for archiveList
     *
     * Archive a list.
     *
     */
    public function testArchiveList()
    {
    }

    /**
     * Test case for createList
     *
     * Create a List.
     *
     */
    public function testCreateList()
    {
    }

    /**
     * Test case for deleteList
     *
     * Delete a List.
     *
     */
    public function testDeleteList()
    {
    }

    /**
     * Test case for getList
     *
     * Show a list parameters.
     *
     */
    public function testGetList()
    {
    }

    /**
     * Test case for listLists
     *
     * Show all lists.
     *
     */
    public function testListLists()
    {
    }

    /**
     * Test case for patchList
     *
     * Update a list parameters.
     *
     */
    public function testPatchList()
    {
    }

    /**
     * Test case for unarchiveList
     *
     * Unarchive a list.
     *
     */
    public function testUnarchiveList()
    {
    }
}
