<?php
/**
 * SegmentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Cakemail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cakemail API
 *
 * The Cakemail API exposes multiple APIs including Authentication, Marketing, Contact, Transactional, Analytic, Content, Account and Partner.
 *
 * The version of the OpenAPI document: 1.0.0-alpha5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Cakemail;

use \Cakemail\Configuration;
use \Cakemail\ApiException;
use \Cakemail\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SegmentApiTest Class Doc Comment
 *
 * @category Class
 * @package  Cakemail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SegmentApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createSegment
     *
     * Create a segment.
     *
     */
    public function testCreateSegment()
    {
    }

    /**
     * Test case for deleteSegment
     *
     * Delete a segment.
     *
     */
    public function testDeleteSegment()
    {
    }

    /**
     * Test case for getSegment
     *
     * Show a segment details.
     *
     */
    public function testGetSegment()
    {
    }

    /**
     * Test case for listSegments
     *
     * Show all segments.
     *
     */
    public function testListSegments()
    {
    }

    /**
     * Test case for patchSegment
     *
     * Update a segment.
     *
     */
    public function testPatchSegment()
    {
    }
}
