<?php
/**
 * SenderApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Cakemail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cakemail API
 *
 * The Cakemail API exposes multiple APIs including Authentication, Marketing, Contact, Transactional, Analytic, Content, Account and Partner.
 *
 * The version of the OpenAPI document: 1.0.0-alpha5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Cakemail;

use \Cakemail\Configuration;
use \Cakemail\ApiException;
use \Cakemail\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SenderApiTest Class Doc Comment
 *
 * @category Class
 * @package  Cakemail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SenderApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for confirmSender
     *
     * Confirm a sender.
     *
     */
    public function testConfirmSender()
    {
    }

    /**
     * Test case for createSender
     *
     * Add a sender.
     *
     */
    public function testCreateSender()
    {
    }

    /**
     * Test case for deleteSender
     *
     * Delete a sender.
     *
     */
    public function testDeleteSender()
    {
    }

    /**
     * Test case for getSender
     *
     * Show a sender details.
     *
     */
    public function testGetSender()
    {
    }

    /**
     * Test case for listSenders
     *
     * Show all senders.
     *
     */
    public function testListSenders()
    {
    }

    /**
     * Test case for patchSender
     *
     * Update a sender.
     *
     */
    public function testPatchSender()
    {
    }

    /**
     * Test case for resendConfirmationEmail
     *
     * Resend confirmation email.
     *
     */
    public function testResendConfirmationEmail()
    {
    }
}
