<?php
/**
 * SubAccountApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Cakemail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cakemail API
 *
 * The Cakemail API exposes multiple APIs including Authentication, Marketing, Contact, Transactional, Analytic, Content, Account and Partner.
 *
 * The version of the OpenAPI document: 1.0.0-alpha5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Cakemail;

use \Cakemail\Configuration;
use \Cakemail\ApiException;
use \Cakemail\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SubAccountApiTest Class Doc Comment
 *
 * @category Class
 * @package  Cakemail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SubAccountApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createAccount
     *
     * Create a sub-account.
     *
     */
    public function testCreateAccount()
    {
    }

    /**
     * Test case for deleteAccount
     *
     * Delete a sub-account.
     *
     */
    public function testDeleteAccount()
    {
    }

    /**
     * Test case for getAccount
     *
     * Show a sub-account details.
     *
     */
    public function testGetAccount()
    {
    }

    /**
     * Test case for listAccounts
     *
     * Show all sub-accounts.
     *
     */
    public function testListAccounts()
    {
    }

    /**
     * Test case for patchAccount
     *
     * Update a sub-account.
     *
     */
    public function testPatchAccount()
    {
    }

    /**
     * Test case for suspendAccount
     *
     * Suspend a sub-account.
     *
     */
    public function testSuspendAccount()
    {
    }

    /**
     * Test case for unsuspendAccount
     *
     * Unsuspend a sub-account.
     *
     */
    public function testUnsuspendAccount()
    {
    }
}
