<?php
/**
 * UserApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Cakemail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cakemail API
 *
 * The Cakemail API exposes multiple APIs including Authentication, Marketing, Contact, Transactional, Analytic, Content, Account and Partner.
 *
 * The version of the OpenAPI document: 1.0.0-alpha5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Cakemail;

use \Cakemail\Configuration;
use \Cakemail\ApiException;
use \Cakemail\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UserApiTest Class Doc Comment
 *
 * @category Class
 * @package  Cakemail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UserApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createUser
     *
     * Create a user.
     *
     */
    public function testCreateUser()
    {
    }

    /**
     * Test case for deleteUser
     *
     * Delete a user.
     *
     */
    public function testDeleteUser()
    {
    }

    /**
     * Test case for getSelfUser
     *
     * Show my user details.
     *
     */
    public function testGetSelfUser()
    {
    }

    /**
     * Test case for getUser
     *
     * Show a user details.
     *
     */
    public function testGetUser()
    {
    }

    /**
     * Test case for listUsers
     *
     * Show all users in my account.
     *
     */
    public function testListUsers()
    {
    }

    /**
     * Test case for patchUser
     *
     * Update a user.
     *
     */
    public function testPatchUser()
    {
    }

    /**
     * Test case for resetPassword
     *
     * Reset my password.
     *
     */
    public function testResetPassword()
    {
    }

    /**
     * Test case for resetPasswordConfirm
     *
     * Reset password confirmation.
     *
     */
    public function testResetPasswordConfirm()
    {
    }

    /**
     * Test case for resetUserPassword
     *
     * Reset a user password.
     *
     */
    public function testResetUserPassword()
    {
    }

    /**
     * Test case for suspendUser
     *
     * Suspend a user.
     *
     */
    public function testSuspendUser()
    {
    }

    /**
     * Test case for unsuspendUser
     *
     * Unsuspend a user.
     *
     */
    public function testUnsuspendUser()
    {
    }
}
